version: "3"

services:
  web:
    build: .
    links:
      - redis
      - rethink
    command: nodemon --debug=5858
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5858:5858"
  redis:
    image: redis
    ports:
      - "6379:6379"
  rethink:
    image: rethinkdb
    ports:
      - "8080:8080"